/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as DiffRouteImport } from './routes/diff'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkingTerminalRouteImport } from './routes/working/terminal'
import { Route as WatchingUnifiedRouteImport } from './routes/watching/unified'
import { Route as WatchingOverviewRouteImport } from './routes/watching/overview'
import { Route as WatchingLocalRouteImport } from './routes/watching/local'
import { Route as WatchingApiRouteImport } from './routes/watching/api'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as GuardingRulesRouteImport } from './routes/guarding/rules'
import { Route as GuardingGlobalRulesRouteImport } from './routes/guarding/global-rules'
import { Route as GuardingClaudeMdRouteImport } from './routes/guarding/claude-md'
import { Route as WatchingVoiceIndexRouteImport } from './routes/watching/voice/index'
import { Route as WatchingSessionsIndexRouteImport } from './routes/watching/sessions/index'
import { Route as WatchingMemoriesIndexRouteImport } from './routes/watching/memories/index'
import { Route as WatchingKnowledgeIndexRouteImport } from './routes/watching/knowledge/index'
import { Route as WatchingGraphIndexRouteImport } from './routes/watching/graph/index'
import { Route as ResearchNotebooksIndexRouteImport } from './routes/research/notebooks/index'
import { Route as GuardingSkillsIndexRouteImport } from './routes/guarding/skills/index'
import { Route as WatchingSessionsSessionIdRouteImport } from './routes/watching/sessions/$sessionId'
import { Route as GuardingSkillsNewRouteImport } from './routes/guarding/skills/new'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DiffRoute = DiffRouteImport.update({
  id: '/diff',
  path: '/diff',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/diff.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkingTerminalRoute = WorkingTerminalRouteImport.update({
  id: '/working/terminal',
  path: '/working/terminal',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/working/terminal.lazy').then((d) => d.Route),
)
const WatchingUnifiedRoute = WatchingUnifiedRouteImport.update({
  id: '/watching/unified',
  path: '/watching/unified',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchingOverviewRoute = WatchingOverviewRouteImport.update({
  id: '/watching/overview',
  path: '/watching/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchingLocalRoute = WatchingLocalRouteImport.update({
  id: '/watching/local',
  path: '/watching/local',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchingApiRoute = WatchingApiRouteImport.update({
  id: '/watching/api',
  path: '/watching/api',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/projects/$slug.lazy').then((d) => d.Route),
)
const GuardingRulesRoute = GuardingRulesRouteImport.update({
  id: '/guarding/rules',
  path: '/guarding/rules',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/guarding/rules.lazy').then((d) => d.Route),
)
const GuardingGlobalRulesRoute = GuardingGlobalRulesRouteImport.update({
  id: '/guarding/global-rules',
  path: '/guarding/global-rules',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/guarding/global-rules.lazy').then((d) => d.Route),
)
const GuardingClaudeMdRoute = GuardingClaudeMdRouteImport.update({
  id: '/guarding/claude-md',
  path: '/guarding/claude-md',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/guarding/claude-md.lazy').then((d) => d.Route),
)
const WatchingVoiceIndexRoute = WatchingVoiceIndexRouteImport.update({
  id: '/watching/voice/',
  path: '/watching/voice/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchingSessionsIndexRoute = WatchingSessionsIndexRouteImport.update({
  id: '/watching/sessions/',
  path: '/watching/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchingMemoriesIndexRoute = WatchingMemoriesIndexRouteImport.update({
  id: '/watching/memories/',
  path: '/watching/memories/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchingKnowledgeIndexRoute = WatchingKnowledgeIndexRouteImport.update({
  id: '/watching/knowledge/',
  path: '/watching/knowledge/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchingGraphIndexRoute = WatchingGraphIndexRouteImport.update({
  id: '/watching/graph/',
  path: '/watching/graph/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchNotebooksIndexRoute = ResearchNotebooksIndexRouteImport.update({
  id: '/research/notebooks/',
  path: '/research/notebooks/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardingSkillsIndexRoute = GuardingSkillsIndexRouteImport.update({
  id: '/guarding/skills/',
  path: '/guarding/skills/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/guarding/skills/index.lazy').then((d) => d.Route),
)
const WatchingSessionsSessionIdRoute =
  WatchingSessionsSessionIdRouteImport.update({
    id: '/watching/sessions/$sessionId',
    path: '/watching/sessions/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuardingSkillsNewRoute = GuardingSkillsNewRouteImport.update({
  id: '/guarding/skills/new',
  path: '/guarding/skills/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diff': typeof DiffRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/guarding/claude-md': typeof GuardingClaudeMdRoute
  '/guarding/global-rules': typeof GuardingGlobalRulesRoute
  '/guarding/rules': typeof GuardingRulesRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/watching/api': typeof WatchingApiRoute
  '/watching/local': typeof WatchingLocalRoute
  '/watching/overview': typeof WatchingOverviewRoute
  '/watching/unified': typeof WatchingUnifiedRoute
  '/working/terminal': typeof WorkingTerminalRoute
  '/guarding/skills/new': typeof GuardingSkillsNewRoute
  '/watching/sessions/$sessionId': typeof WatchingSessionsSessionIdRoute
  '/guarding/skills/': typeof GuardingSkillsIndexRoute
  '/research/notebooks/': typeof ResearchNotebooksIndexRoute
  '/watching/graph/': typeof WatchingGraphIndexRoute
  '/watching/knowledge/': typeof WatchingKnowledgeIndexRoute
  '/watching/memories/': typeof WatchingMemoriesIndexRoute
  '/watching/sessions/': typeof WatchingSessionsIndexRoute
  '/watching/voice/': typeof WatchingVoiceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diff': typeof DiffRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/guarding/claude-md': typeof GuardingClaudeMdRoute
  '/guarding/global-rules': typeof GuardingGlobalRulesRoute
  '/guarding/rules': typeof GuardingRulesRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/watching/api': typeof WatchingApiRoute
  '/watching/local': typeof WatchingLocalRoute
  '/watching/overview': typeof WatchingOverviewRoute
  '/watching/unified': typeof WatchingUnifiedRoute
  '/working/terminal': typeof WorkingTerminalRoute
  '/guarding/skills/new': typeof GuardingSkillsNewRoute
  '/watching/sessions/$sessionId': typeof WatchingSessionsSessionIdRoute
  '/guarding/skills': typeof GuardingSkillsIndexRoute
  '/research/notebooks': typeof ResearchNotebooksIndexRoute
  '/watching/graph': typeof WatchingGraphIndexRoute
  '/watching/knowledge': typeof WatchingKnowledgeIndexRoute
  '/watching/memories': typeof WatchingMemoriesIndexRoute
  '/watching/sessions': typeof WatchingSessionsIndexRoute
  '/watching/voice': typeof WatchingVoiceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diff': typeof DiffRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/guarding/claude-md': typeof GuardingClaudeMdRoute
  '/guarding/global-rules': typeof GuardingGlobalRulesRoute
  '/guarding/rules': typeof GuardingRulesRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/watching/api': typeof WatchingApiRoute
  '/watching/local': typeof WatchingLocalRoute
  '/watching/overview': typeof WatchingOverviewRoute
  '/watching/unified': typeof WatchingUnifiedRoute
  '/working/terminal': typeof WorkingTerminalRoute
  '/guarding/skills/new': typeof GuardingSkillsNewRoute
  '/watching/sessions/$sessionId': typeof WatchingSessionsSessionIdRoute
  '/guarding/skills/': typeof GuardingSkillsIndexRoute
  '/research/notebooks/': typeof ResearchNotebooksIndexRoute
  '/watching/graph/': typeof WatchingGraphIndexRoute
  '/watching/knowledge/': typeof WatchingKnowledgeIndexRoute
  '/watching/memories/': typeof WatchingMemoriesIndexRoute
  '/watching/sessions/': typeof WatchingSessionsIndexRoute
  '/watching/voice/': typeof WatchingVoiceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diff'
    | '/profile'
    | '/settings'
    | '/guarding/claude-md'
    | '/guarding/global-rules'
    | '/guarding/rules'
    | '/projects/$slug'
    | '/watching/api'
    | '/watching/local'
    | '/watching/overview'
    | '/watching/unified'
    | '/working/terminal'
    | '/guarding/skills/new'
    | '/watching/sessions/$sessionId'
    | '/guarding/skills/'
    | '/research/notebooks/'
    | '/watching/graph/'
    | '/watching/knowledge/'
    | '/watching/memories/'
    | '/watching/sessions/'
    | '/watching/voice/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diff'
    | '/profile'
    | '/settings'
    | '/guarding/claude-md'
    | '/guarding/global-rules'
    | '/guarding/rules'
    | '/projects/$slug'
    | '/watching/api'
    | '/watching/local'
    | '/watching/overview'
    | '/watching/unified'
    | '/working/terminal'
    | '/guarding/skills/new'
    | '/watching/sessions/$sessionId'
    | '/guarding/skills'
    | '/research/notebooks'
    | '/watching/graph'
    | '/watching/knowledge'
    | '/watching/memories'
    | '/watching/sessions'
    | '/watching/voice'
  id:
    | '__root__'
    | '/'
    | '/diff'
    | '/profile'
    | '/settings'
    | '/guarding/claude-md'
    | '/guarding/global-rules'
    | '/guarding/rules'
    | '/projects/$slug'
    | '/watching/api'
    | '/watching/local'
    | '/watching/overview'
    | '/watching/unified'
    | '/working/terminal'
    | '/guarding/skills/new'
    | '/watching/sessions/$sessionId'
    | '/guarding/skills/'
    | '/research/notebooks/'
    | '/watching/graph/'
    | '/watching/knowledge/'
    | '/watching/memories/'
    | '/watching/sessions/'
    | '/watching/voice/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiffRoute: typeof DiffRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  GuardingClaudeMdRoute: typeof GuardingClaudeMdRoute
  GuardingGlobalRulesRoute: typeof GuardingGlobalRulesRoute
  GuardingRulesRoute: typeof GuardingRulesRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  WatchingApiRoute: typeof WatchingApiRoute
  WatchingLocalRoute: typeof WatchingLocalRoute
  WatchingOverviewRoute: typeof WatchingOverviewRoute
  WatchingUnifiedRoute: typeof WatchingUnifiedRoute
  WorkingTerminalRoute: typeof WorkingTerminalRoute
  GuardingSkillsNewRoute: typeof GuardingSkillsNewRoute
  WatchingSessionsSessionIdRoute: typeof WatchingSessionsSessionIdRoute
  GuardingSkillsIndexRoute: typeof GuardingSkillsIndexRoute
  ResearchNotebooksIndexRoute: typeof ResearchNotebooksIndexRoute
  WatchingGraphIndexRoute: typeof WatchingGraphIndexRoute
  WatchingKnowledgeIndexRoute: typeof WatchingKnowledgeIndexRoute
  WatchingMemoriesIndexRoute: typeof WatchingMemoriesIndexRoute
  WatchingSessionsIndexRoute: typeof WatchingSessionsIndexRoute
  WatchingVoiceIndexRoute: typeof WatchingVoiceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diff': {
      id: '/diff'
      path: '/diff'
      fullPath: '/diff'
      preLoaderRoute: typeof DiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/working/terminal': {
      id: '/working/terminal'
      path: '/working/terminal'
      fullPath: '/working/terminal'
      preLoaderRoute: typeof WorkingTerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watching/unified': {
      id: '/watching/unified'
      path: '/watching/unified'
      fullPath: '/watching/unified'
      preLoaderRoute: typeof WatchingUnifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watching/overview': {
      id: '/watching/overview'
      path: '/watching/overview'
      fullPath: '/watching/overview'
      preLoaderRoute: typeof WatchingOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watching/local': {
      id: '/watching/local'
      path: '/watching/local'
      fullPath: '/watching/local'
      preLoaderRoute: typeof WatchingLocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watching/api': {
      id: '/watching/api'
      path: '/watching/api'
      fullPath: '/watching/api'
      preLoaderRoute: typeof WatchingApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guarding/rules': {
      id: '/guarding/rules'
      path: '/guarding/rules'
      fullPath: '/guarding/rules'
      preLoaderRoute: typeof GuardingRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guarding/global-rules': {
      id: '/guarding/global-rules'
      path: '/guarding/global-rules'
      fullPath: '/guarding/global-rules'
      preLoaderRoute: typeof GuardingGlobalRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guarding/claude-md': {
      id: '/guarding/claude-md'
      path: '/guarding/claude-md'
      fullPath: '/guarding/claude-md'
      preLoaderRoute: typeof GuardingClaudeMdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watching/voice/': {
      id: '/watching/voice/'
      path: '/watching/voice'
      fullPath: '/watching/voice/'
      preLoaderRoute: typeof WatchingVoiceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watching/sessions/': {
      id: '/watching/sessions/'
      path: '/watching/sessions'
      fullPath: '/watching/sessions/'
      preLoaderRoute: typeof WatchingSessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watching/memories/': {
      id: '/watching/memories/'
      path: '/watching/memories'
      fullPath: '/watching/memories/'
      preLoaderRoute: typeof WatchingMemoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watching/knowledge/': {
      id: '/watching/knowledge/'
      path: '/watching/knowledge'
      fullPath: '/watching/knowledge/'
      preLoaderRoute: typeof WatchingKnowledgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watching/graph/': {
      id: '/watching/graph/'
      path: '/watching/graph'
      fullPath: '/watching/graph/'
      preLoaderRoute: typeof WatchingGraphIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/notebooks/': {
      id: '/research/notebooks/'
      path: '/research/notebooks'
      fullPath: '/research/notebooks/'
      preLoaderRoute: typeof ResearchNotebooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guarding/skills/': {
      id: '/guarding/skills/'
      path: '/guarding/skills'
      fullPath: '/guarding/skills/'
      preLoaderRoute: typeof GuardingSkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watching/sessions/$sessionId': {
      id: '/watching/sessions/$sessionId'
      path: '/watching/sessions/$sessionId'
      fullPath: '/watching/sessions/$sessionId'
      preLoaderRoute: typeof WatchingSessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guarding/skills/new': {
      id: '/guarding/skills/new'
      path: '/guarding/skills/new'
      fullPath: '/guarding/skills/new'
      preLoaderRoute: typeof GuardingSkillsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiffRoute: DiffRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  GuardingClaudeMdRoute: GuardingClaudeMdRoute,
  GuardingGlobalRulesRoute: GuardingGlobalRulesRoute,
  GuardingRulesRoute: GuardingRulesRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  WatchingApiRoute: WatchingApiRoute,
  WatchingLocalRoute: WatchingLocalRoute,
  WatchingOverviewRoute: WatchingOverviewRoute,
  WatchingUnifiedRoute: WatchingUnifiedRoute,
  WorkingTerminalRoute: WorkingTerminalRoute,
  GuardingSkillsNewRoute: GuardingSkillsNewRoute,
  WatchingSessionsSessionIdRoute: WatchingSessionsSessionIdRoute,
  GuardingSkillsIndexRoute: GuardingSkillsIndexRoute,
  ResearchNotebooksIndexRoute: ResearchNotebooksIndexRoute,
  WatchingGraphIndexRoute: WatchingGraphIndexRoute,
  WatchingKnowledgeIndexRoute: WatchingKnowledgeIndexRoute,
  WatchingMemoriesIndexRoute: WatchingMemoriesIndexRoute,
  WatchingSessionsIndexRoute: WatchingSessionsIndexRoute,
  WatchingVoiceIndexRoute: WatchingVoiceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
