import { sqliteTable, text, integer, index, uniqueIndex } from "drizzle-orm/sqlite-core";
import { sql } from "drizzle-orm";

/**
 * Generic key/value bag for app-level state that does not warrant its own
 * table — last-active project, schema version markers, ad-hoc settings.
 *
 * Drizzle's TypeScript types enforce column types at compile time. SQLite's
 * STRICT keyword would catch the same class of bugs at runtime but is not
 * generated by drizzle-kit and would not survive a future PG migration
 * anyway, so we lean on the type system instead.
 */
export const appState = sqliteTable(
  "app_state",
  {
    key: text("key").primaryKey(),
    value: text("value").notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .notNull()
      .default(sql`(unixepoch() * 1000)`),
  },
  () => ({}),
);

export type AppStateRow = typeof appState.$inferSelect;
export type NewAppStateRow = typeof appState.$inferInsert;

/**
 * Append-only history of file contents written through claude-fs. Every
 * successful write creates a row with the *previous* content unless the
 * hash matches the most recent backup for that path (no-op write).
 *
 * The relative path is stored, not the absolute one — claude home can move
 * across machines and we want backups to remain meaningful when it does.
 *
 * `scope` is the namespace key: "global" for ~/.claude or "project:<slug>"
 * for a project's local .claude/. Without this column the same relPath
 * (e.g. CLAUDE.md) across scopes would collide on dedupe and history.
 */
export const fileBackups = sqliteTable(
  "file_backups",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    scope: text("scope").notNull().default("global"),
    filePath: text("file_path").notNull(),
    content: text("content").notNull(),
    contentHash: text("content_hash").notNull(),
    createdAt: integer("created_at", { mode: "timestamp_ms" })
      .notNull()
      .default(sql`(unixepoch() * 1000)`),
  },
  (t) => [
    index("file_backups_scope_path_idx").on(t.scope, t.filePath),
    index("file_backups_scope_path_created_idx").on(
      t.scope,
      t.filePath,
      t.createdAt,
    ),
  ],
);

export type FileBackupRow = typeof fileBackups.$inferSelect;
export type NewFileBackupRow = typeof fileBackups.$inferInsert;

/**
 * User-added project roots. Complementary to the `HAETAE_PROJECT_ROOTS`
 * env var: env entries are a read-only seed (machine setup / CI / first
 * boot), DB entries are added through the Settings UI and persisted
 * across runs.
 *
 * `absolutePath` is unique — a CHECK at the application layer also
 * rejects insertions that overlap with the env list.
 */
export const projectRoots = sqliteTable("project_roots", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  absolutePath: text("absolute_path").notNull().unique(),
  addedAt: integer("added_at", { mode: "timestamp_ms" })
    .notNull()
    .default(sql`(unixepoch() * 1000)`),
});

export type ProjectRootRow = typeof projectRoots.$inferSelect;
export type NewProjectRootRow = typeof projectRoots.$inferInsert;

/**
 * One row per billable Claude Code assistant message extracted from a
 * JSONL session log. The `(session_id, message_id)` pair is the natural
 * key — re-running the indexer over the same file is a no-op because the
 * UNIQUE constraint causes ON CONFLICT IGNORE inserts to skip dupes.
 *
 * `cost_usd_micro` stores cost as integer micro-USD (USD × 1_000_000) so
 * SQLite never sees floats — sums and aggregations stay exact.
 * Application layer divides by 1e6 when surfacing to the UI.
 */
export const usageEvents = sqliteTable(
  "usage_events",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    sessionId: text("session_id").notNull(),
    messageId: text("message_id").notNull(),
    projectPath: text("project_path").notNull(),
    model: text("model").notNull(),
    ts: integer("ts").notNull(),
    inputTokens: integer("input_tokens").notNull().default(0),
    outputTokens: integer("output_tokens").notNull().default(0),
    cacheCreationTokens: integer("cache_creation_tokens").notNull().default(0),
    cacheReadTokens: integer("cache_read_tokens").notNull().default(0),
    costUsdMicro: integer("cost_usd_micro").notNull().default(0),
  },
  (t) => [
    // Natural dedupe key — INSERT OR IGNORE relies on this UNIQUE
    // constraint so re-indexing the same JSONL is a no-op.
    uniqueIndex("usage_events_session_message_uniq").on(t.sessionId, t.messageId),
    index("usage_events_ts_idx").on(t.ts),
    index("usage_events_project_idx").on(t.projectPath),
    index("usage_events_model_idx").on(t.model),
  ],
);

export type UsageEventRow = typeof usageEvents.$inferSelect;
export type NewUsageEventRow = typeof usageEvents.$inferInsert;

/**
 * Incremental cursor — tells the indexer where it left off in each JSONL
 * file. On re-run we read the file's current size + mtime; if either
 * grew, we resume from `last_offset` instead of re-parsing the whole
 * thing. If `last_mtime` *decreased* (file rotated, restored from backup)
 * we treat it as a different file and reparse from offset 0.
 */
export const usageFileCursor = sqliteTable("usage_file_cursor", {
  filePath: text("file_path").primaryKey(),
  lastOffset: integer("last_offset").notNull().default(0),
  lastMtime: integer("last_mtime").notNull().default(0),
});

export type UsageFileCursorRow = typeof usageFileCursor.$inferSelect;
export type NewUsageFileCursorRow = typeof usageFileCursor.$inferInsert;

/**
 * Mirror of Anthropic's Organization Admin API reports (usage_report +
 * cost_report) — one row per time bucket × model × workspace × api key.
 * Single table because both reports share that key shape; cost rows
 * fill in `cost_usd_micro` while usage rows fill the token columns,
 * and an INSERT OR REPLACE merge keeps the latest fetch authoritative.
 *
 * The four "dimension" columns default to empty strings (not NULL) so
 * the UNIQUE constraint stays simple — SQLite treats NULLs as distinct
 * which would let identical buckets duplicate.
 */
export const usageApiEvents = sqliteTable(
  "usage_api_events",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    /** Unix ms — start of the bucket Anthropic returned. */
    bucketStart: integer("bucket_start").notNull(),
    /** "1d" / "1h" — the bucket_width param echoed back. */
    bucketWidth: text("bucket_width").notNull(),
    model: text("model").notNull().default(""),
    /** Empty string == "no workspace dimension" (org-wide row). */
    workspaceId: text("workspace_id").notNull().default(""),
    apiKeyId: text("api_key_id").notNull().default(""),
    inputTokens: integer("input_tokens").notNull().default(0),
    outputTokens: integer("output_tokens").notNull().default(0),
    cacheCreationTokens: integer("cache_creation_tokens").notNull().default(0),
    cacheReadTokens: integer("cache_read_tokens").notNull().default(0),
    /** Integer micro-USD, same scale as usage_events. */
    costUsdMicro: integer("cost_usd_micro").notNull().default(0),
    /** When the server fetched this bucket from Anthropic — drives cache
        age display + TTL decisions. */
    fetchedAt: integer("fetched_at").notNull(),
  },
  (t) => [
    uniqueIndex("usage_api_events_bucket_uniq").on(
      t.bucketStart,
      t.bucketWidth,
      t.model,
      t.workspaceId,
      t.apiKeyId,
    ),
    index("usage_api_events_bucket_idx").on(t.bucketStart),
    index("usage_api_events_model_idx").on(t.model),
  ],
);

export type UsageApiEventRow = typeof usageApiEvents.$inferSelect;
export type NewUsageApiEventRow = typeof usageApiEvents.$inferInsert;

/**
 * Every JSONL entry from ~/.claude/projects/<encoded>/<uuid>.jsonl stored verbatim
 * (text content only — base64 image payloads are stripped).
 *
 * `uuid` is the natural dedup key: Claude Code assigns a unique uuid to
 * each entry, so INSERT OR IGNORE on re-indexing is safe.
 *
 * Compact-related columns are populated only for:
 *   - type="system" subtype="compact_boundary"  → is_compact_summary=false,
 *     compact_* filled
 *   - type="user" isCompactSummary=true (anchor) → is_compact_summary=true,
 *     compact_* null
 */
export const sessionMessages = sqliteTable(
  "session_messages",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    uuid: text("uuid").notNull(),
    parentUuid: text("parent_uuid"),
    sessionId: text("session_id").notNull(),
    projectPath: text("project_path").notNull(),
    /** 'user' | 'assistant' | 'system' | 'attachment' */
    type: text("type").notNull(),
    /** 'compact_boundary' or null */
    subtype: text("subtype"),
    /** Extracted plain text. null for tool-use-only assistant turns. */
    content: text("content"),
    ts: integer("ts").notNull(),
    isCompactSummary: integer("is_compact_summary", { mode: "boolean" })
      .notNull()
      .default(false),
    /** 'manual' | 'auto' — set on compact_boundary rows */
    compactTrigger: text("compact_trigger"),
    compactPreTokens: integer("compact_pre_tokens"),
    compactPostTokens: integer("compact_post_tokens"),
  },
  (t) => [
    uniqueIndex("session_messages_uuid_uniq").on(t.uuid),
    index("session_messages_session_idx").on(t.sessionId),
    index("session_messages_project_ts_idx").on(t.projectPath, t.ts),
    index("session_messages_compact_summary_idx").on(t.isCompactSummary),
  ],
);

export type SessionMessageRow = typeof sessionMessages.$inferSelect;
export type NewSessionMessageRow = typeof sessionMessages.$inferInsert;

/**
 * Project-scoped memory layer. Seeded from compact summaries automatically;
 * designed to also accept manually-added entries later.
 *
 * `summaryUuid` links back to the session_messages row (is_compact_summary=1)
 * that sourced this memory — UNIQUE so re-materializing is idempotent.
 * NULL for manually-created memories.
 */
export const memories = sqliteTable(
  "memories",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    /** FK → session_messages.uuid where is_compact_summary=1. Null for manual. */
    summaryUuid: text("summary_uuid").unique(),
    sessionId: text("session_id").notNull(),
    projectPath: text("project_path").notNull(),
    content: text("content").notNull(),
    /** 'compact_summary' | 'manual' */
    source: text("source").notNull().default("compact_summary"),
    /** compact trigger when source='compact_summary': 'manual' | 'auto' */
    compactTrigger: text("compact_trigger"),
    compactPreTokens: integer("compact_pre_tokens"),
    compactPostTokens: integer("compact_post_tokens"),
    ts: integer("ts").notNull(),
    createdAt: integer("created_at", { mode: "timestamp_ms" })
      .notNull()
      .default(sql`(unixepoch() * 1000)`),
  },
  (t) => [
    index("memories_project_ts_idx").on(t.projectPath, t.ts),
    index("memories_session_idx").on(t.sessionId),
  ],
);

export type MemoryRow = typeof memories.$inferSelect;
export type NewMemoryRow = typeof memories.$inferInsert;

/**
 * One living wiki page per project. Generated by LLM from all session_messages
 * for that project. Updated incrementally as new sessions are indexed.
 *
 * `projectPath` is the unique key — there is exactly one wiki page per project.
 * `generatedAt` tracks the last LLM synthesis run; `sessionsCovered` records
 * how many sessions were folded in so the UI can detect stale pages.
 *
 * `content` is raw markdown produced by the model — the UI renders it as-is.
 */
export const projectWiki = sqliteTable(
  "project_wiki",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    projectPath: text("project_path").notNull().unique(),
    /** Markdown content produced by the wiki synthesizer. */
    content: text("content").notNull(),
    /** Cumulative count of session_messages folded into the wiki across all
        generations (not just the last). */
    messagesCovered: integer("messages_covered").notNull().default(0),
    /** Keyset watermark — ts of the last message folded into the wiki. The
        next incremental run reads messages strictly after (lastMessageTs,
        lastMessageUuid) so nothing is re-summarized and nothing is skipped. */
    lastMessageTs: integer("last_message_ts").notNull().default(0),
    /** Keyset watermark tiebreaker — uuid of the last folded message, used
        when multiple messages share the same ts. */
    lastMessageUuid: text("last_message_uuid").notNull().default(""),
    /** Unix ms when the last LLM synthesis completed. */
    generatedAt: integer("generated_at").notNull(),
    /** Short summary / title line for the project (first h1 or first sentence). */
    summary: text("summary"),
    /** Model used for last generation, e.g. 'claude-opus-4-7'. */
    model: text("model").notNull().default("claude-opus-4-7"),
    createdAt: integer("created_at", { mode: "timestamp_ms" })
      .notNull()
      .default(sql`(unixepoch() * 1000)`),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .notNull()
      .default(sql`(unixepoch() * 1000)`),
  },
  (t) => [
    index("project_wiki_project_idx").on(t.projectPath),
    index("project_wiki_generated_at_idx").on(t.generatedAt),
  ],
);

export type ProjectWikiRow = typeof projectWiki.$inferSelect;
export type NewProjectWikiRow = typeof projectWiki.$inferInsert;

/**
 * Append-only snapshots of prior `project_wiki` versions. A snapshot is taken
 * immediately before a wiki is overwritten (regenerate / reset / rollback) so
 * a bad generation can be rolled back.
 *
 * The full restorable state is captured — not just `content` — because a
 * rollback must also restore the keyset watermark (`last_message_*`) and
 * `messages_covered`, otherwise the incremental engine would be out of sync
 * (content rewound but watermark left ahead → the gap is never re-folded).
 */
export const projectWikiHistory = sqliteTable(
  "project_wiki_history",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    projectPath: text("project_path").notNull(),
    content: text("content").notNull(),
    summary: text("summary"),
    model: text("model").notNull(),
    messagesCovered: integer("messages_covered").notNull(),
    lastMessageTs: integer("last_message_ts").notNull(),
    lastMessageUuid: text("last_message_uuid").notNull(),
    /** When this version was originally generated. */
    generatedAt: integer("generated_at").notNull(),
    /** When this version was snapshotted (i.e. superseded). */
    archivedAt: integer("archived_at", { mode: "timestamp_ms" })
      .notNull()
      .default(sql`(unixepoch() * 1000)`),
  },
  (t) => [index("project_wiki_history_project_idx").on(t.projectPath, t.archivedAt)],
);

export type ProjectWikiHistoryRow = typeof projectWikiHistory.$inferSelect;
export type NewProjectWikiHistoryRow = typeof projectWikiHistory.$inferInsert;

/**
 * Typed knowledge ontology per project — the "semantic" graph layer (vs the
 * structural session/file graph). The LLM agent extracts concept nodes and
 * TYPED relations (supports / extends / depends_on / part_of / contradicts /
 * similar) from the project wiki. Stored as a JSON blob since it's read whole
 * and regenerated on demand (like the wiki — no per-view LLM cost).
 */
export const projectOntology = sqliteTable(
  "project_ontology",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    projectPath: text("project_path").notNull().unique(),
    /** JSON: { concepts: [...], relations: [...] } */
    content: text("content").notNull(),
    /** Model used for extraction. */
    model: text("model").notNull(),
    /** Unix ms when extraction completed. */
    generatedAt: integer("generated_at").notNull(),
    createdAt: integer("created_at", { mode: "timestamp_ms" })
      .notNull()
      .default(sql`(unixepoch() * 1000)`),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .notNull()
      .default(sql`(unixepoch() * 1000)`),
  },
  (t) => [index("project_ontology_project_idx").on(t.projectPath)],
);

export type ProjectOntologyRow = typeof projectOntology.$inferSelect;
export type NewProjectOntologyRow = typeof projectOntology.$inferInsert;

/**
 * Single-row, cross-project profile of the USER — their voice, preferences, and
 * working style, synthesized from their own messages across all projects. This
 * is the "personal context" layer (the moat): the global analog of project_wiki.
 * `scope` is a singleton key ('global') so regeneration upserts one row.
 */
export const userProfile = sqliteTable("user_profile", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  scope: text("scope").notNull().unique().default("global"),
  /** Markdown profile. */
  content: text("content").notNull(),
  model: text("model").notNull(),
  /** User messages folded into the last synthesis. */
  messagesCovered: integer("messages_covered").notNull().default(0),
  generatedAt: integer("generated_at").notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" })
    .notNull()
    .default(sql`(unixepoch() * 1000)`),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" })
    .notNull()
    .default(sql`(unixepoch() * 1000)`),
});

export type UserProfileRow = typeof userProfile.$inferSelect;
export type NewUserProfileRow = typeof userProfile.$inferInsert;

/**
 * Latest self-evaluation of a project's wiki — the "eval loop" that checks the
 * second brain's output stays accurate, current, and on-intent. The agent
 * audits the wiki against the conversations + the user's voice profile and
 * scores it; `content` is the JSON { score, summary, issues[] }.
 */
export const projectEval = sqliteTable(
  "project_eval",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    projectPath: text("project_path").notNull().unique(),
    /** JSON: { score, summary, issues: [{type, severity, detail, fix}] } */
    content: text("content").notNull(),
    score: integer("score").notNull(),
    model: text("model").notNull(),
    generatedAt: integer("generated_at").notNull(),
    createdAt: integer("created_at", { mode: "timestamp_ms" })
      .notNull()
      .default(sql`(unixepoch() * 1000)`),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .notNull()
      .default(sql`(unixepoch() * 1000)`),
  },
  (t) => [index("project_eval_project_idx").on(t.projectPath)],
);

export type ProjectEvalRow = typeof projectEval.$inferSelect;
export type NewProjectEvalRow = typeof projectEval.$inferInsert;

/**
 * Append-only history of eval scores — one row per eval run. project_eval holds
 * only the latest (upserted); this records the trend so we can SEE whether the
 * self-correcting loop (eval → wiki regen) actually lifts trust over time, and
 * detect when added derived layers stop improving it (the layer-depth ceiling).
 */
export const projectEvalHistory = sqliteTable(
  "project_eval_history",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    projectPath: text("project_path").notNull(),
    /** 0–100 overall trust at this run. */
    score: integer("score").notNull(),
    model: text("model").notNull(),
    /** Unix ms when this eval ran. */
    generatedAt: integer("generated_at").notNull(),
  },
  (t) => [index("project_eval_history_project_idx").on(t.projectPath, t.generatedAt)],
);

export type ProjectEvalHistoryRow = typeof projectEvalHistory.$inferSelect;
export type NewProjectEvalHistoryRow = typeof projectEvalHistory.$inferInsert;

/**
 * Atomic notes (Zettelkasten) per project — the wiki split into small
 * single-idea notes linked by [[slug]] wikilinks (Obsidian-style). The note
 * set is regenerated whole from the wiki and read whole, so it's stored as a
 * JSON blob like project_ontology; links live inline in each note's content.
 */
export const projectNotes = sqliteTable(
  "project_notes",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    projectPath: text("project_path").notNull().unique(),
    /** JSON: { notes: [{ slug, title, content }] } — content holds [[slug]] wikilinks. */
    content: text("content").notNull(),
    /** Model used for the split. */
    model: text("model").notNull(),
    /** Unix ms when the split completed. */
    generatedAt: integer("generated_at").notNull(),
    createdAt: integer("created_at", { mode: "timestamp_ms" })
      .notNull()
      .default(sql`(unixepoch() * 1000)`),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .notNull()
      .default(sql`(unixepoch() * 1000)`),
  },
  (t) => [index("project_notes_project_idx").on(t.projectPath)],
);

export type ProjectNotesRow = typeof projectNotes.$inferSelect;
export type NewProjectNotesRow = typeof projectNotes.$inferInsert;

/**
 * Cross-layer links between atomic notes (layer 1) and ontology concepts
 * (layer 2): which concept(s) each note discusses, judged by the agent by
 * meaning. Derived from both notes + ontology; regenerated whole, so stored as
 * one JSON blob per project like the other derived layers.
 */
export const projectLinks = sqliteTable(
  "project_links",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    projectPath: text("project_path").notNull().unique(),
    /** JSON: { links: [{ noteSlug, conceptId }] } */
    content: text("content").notNull(),
    /** Model used for the linking. */
    model: text("model").notNull(),
    /** Unix ms when linking completed. */
    generatedAt: integer("generated_at").notNull(),
    createdAt: integer("created_at", { mode: "timestamp_ms" })
      .notNull()
      .default(sql`(unixepoch() * 1000)`),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .notNull()
      .default(sql`(unixepoch() * 1000)`),
  },
  (t) => [index("project_links_project_idx").on(t.projectPath)],
);

export type ProjectLinksRow = typeof projectLinks.$inferSelect;
export type NewProjectLinksRow = typeof projectLinks.$inferInsert;
